---
name: "♻️ Trunk Check"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  turnk:
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      arguments: --no-progress
